name: publish

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Yarn 1.22.22
        run: npm i -g yarn@1.22.22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint code with standard
        run: yarn run lint

      - name: Run tests
        run: yarn test

      - name: Run bare runtime test
        run: yarn run test:bare

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          registry-url: "https://registry.npmjs.org"

      - name: Install Yarn 1.22.22
        run: npm i -g yarn@1.22.22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
